output:
  elasticsearch:
    hosts:
      - '${ELASTICSEARCH_URL}'
    username: '${ELASTICSEARCH_USERNAME:}'
    password: '${ELASTICSEARCH_PASSWORD:}'
setup:
  kibana:
    host: '${KIBANA_URL}'
heartbeat:
  config:
    monitors:
      path: '${path.config}/monitors.d/*'
      reload:
        enabled: true
        period: 1m
processors:
  - add_cloud_metadata: {}
  - add_host_metadata: {}
  - add_kubernetes_metadata: {}
  - add_observer_metadata: {}
