output:
  elasticsearch:
    hosts:
      - '${ELASTICSEARCH_URL}'
    username: '${ELASTICSEARCH_USERNAME:}'
    password: '${ELASTICSEARCH_PASSWORD:}'
setup:
  kibana:
    host: '${KIBANA_URL}'
filebeat:
  config:
    inputs:
      enabled: true
      path: '${path.config}/inputs.d/*.yml'
      reload:
        enabled: true
    modules:
      enabled: true
      path: '${path.config}/modules.d/*.yml'
      reload:
        enabled: true
  autodiscover:
    providers:
      - type: docker
        hints:
          enabled: true
processors:
  - add_cloud_metadata: {}
  - add_host_metadata: {}
  - add_kubernetes_metadata: {}
